service: meu-servico

provider:
  name: aws
  runtime: nodejs14.x

functions:
  buscarAgendas:
    handler: src/agenda/controller/agendaController.buscarAgendas
    events:
      - http:
          path: agendas
          method: get

  marcarAgendamento:
    handler: src/agendamento/controller/agendamentoController.marcarAgendamento
    events:
      - http:
          path: agendamento
          method: post

plugins:
  - serverless-offline